export const CHANGE_COLLAPSE_COUNT = 'CHANGE_COLLAPSE_COUNT'
export const GET_PERMISSIONS = 'GET_PERMISSIONS'
export const GET_PRODUCTLIST_DATA = 'GET_PRODUCTLIST_DATA'
export const GET_PROCESSLIST_DATA = 'GET_PROCESSLIST_DATA'
